from pathlib import Path

path = Path("backend/tests/test_clinic_settings_rebuild_v0490.py")
source = path.read_text(encoding="utf-8")
old = '''def test_setup_ui_uses_blank_review_draft_and_clear_next_step() -> None:\n    page = (FRONTEND / "src/app/(dashboard)/setup/page.tsx").read_text(encoding="utf-8")\n    importer = (FRONTEND / "src/app/(dashboard)/setup/setup-importer.tsx").read_text(encoding="utf-8")\n    actions = (FRONTEND / "src/app/(dashboard)/setup/actions.ts").read_text(encoding="utf-8")\n    route = (BACKEND / "app/api/routes/clinic_setup_v2.py").read_text(encoding="utf-8")\n    assert "ClinicSetupImporter" in page\n    assert 'accept=".xlsx"' in importer\n    assert "الخانات تبدأ فاضية" in importer\n    assert "قراءة الملف وتعبئة الخانات" in importer\n    assert "تحميل البيانات المحفوظة" in importer\n    assert "التالي: البيانات التاريخية" in importer\n    assert "emptyDraft" in importer\n    assert '\"/clinic/setup-v2/preview\"' in actions\n    assert '\"/clinic/setup-v2/apply-draft\"' in actions\n    assert '@router.post(\"/setup-v2/preview\"' in route\n    assert '@router.post(\"/setup-v2/apply-draft\"' in route\n    assert '@router.get(\"/setup-v2/template\")' in route\n'''
new = '''def test_setup_ui_is_refocused_without_duplicate_service_or_doctor_management() -> None:\n    page = (FRONTEND / "src/app/(dashboard)/setup/page.tsx").read_text(encoding="utf-8")\n    panel = (FRONTEND / "src/app/(dashboard)/setup/clinic-settings-panel.tsx").read_text(encoding="utf-8")\n    importer = (FRONTEND / "src/app/(dashboard)/setup/setup-importer.tsx").read_text(encoding="utf-8")\n    actions = (FRONTEND / "src/app/(dashboard)/setup/actions.ts").read_text(encoding="utf-8")\n    route = (BACKEND / "app/api/routes/clinic_setup_v2.py").read_text(encoding="utf-8")\n\n    assert "ClinicSettingsPanel" in page\n    assert "ClinicSetupImporter" not in page\n    assert 'href=\"/services\"' in panel\n    assert 'href=\"/doctors\"' in panel\n    assert 'href=\"/setup/integration\"' in panel\n    assert "WhatsApp" not in page\n    assert "واتساب والـAutomation" not in page\n    assert "إدارة الخدمات والأسعار" in panel\n    assert "إدارة الدكاترة ومواعيدهم" in panel\n    assert "Knowledge Base الخاصة بـ Tia" in panel\n\n    # The legacy setup importer remains available in code for backwards-compatible\n    # import flows, but it is intentionally no longer rendered on Clinic Settings.\n    assert 'accept=\".xlsx\"' in importer\n    assert "emptyDraft" in importer\n    assert '\"/clinic/setup-v2/preview\"' in actions\n    assert '\"/clinic/setup-v2/apply-draft\"' in actions\n    assert '@router.post(\"/setup-v2/preview\"' in route\n    assert '@router.post(\"/setup-v2/apply-draft\"' in route\n    assert '@router.get(\"/setup-v2/template\")' in route\n'''
if old not in source:
    raise SystemExit("target test block not found")
path.write_text(source.replace(old, new, 1), encoding="utf-8")
