import Link from "next/link";
import { CalendarCheck2, CircleAlert, ContactRound, MessageSquareMore, RadioTower, Workflow } from "lucide-react";
import { PageHeader } from "@/components/page-header"; import { StatCard } from "@/components/stat-card";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Badge } from "@/components/ui/badge";
import { formatDateTime,formatMoney } from "@/lib/format"; import { appointmentLabels,toneForStatus } from "@/lib/status";
import { tiaRequest } from "@/lib/tia/api"; import type { DashboardSummary,HandoffQueueItem } from "@/lib/types";
export default async function DashboardPage(){
 const [summary,handoffs]=await Promise.all([tiaRequest<DashboardSummary>("/dashboard/summary"),tiaRequest<HandoffQueueItem[]>("/inbox/handoffs?limit=5")]);
 return <><PageHeader title="نظرة عامة" description="حالة تشغيل العيادة دلوقتي — حجوزات، عملاء، handoffs وchannels."/>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><StatCard label="عملاء نشطين" value={summary.active_patients} detail="داخل الـCRM" icon={ContactRound}/><StatCard label="حجوزات النهارده" value={summary.appointments_today} detail="بتوقيت القاهرة" icon={CalendarCheck2}/><StatCard label="حجوزات جاية" value={summary.upcoming_appointments} detail="Pending + Confirmed" icon={Workflow}/><StatCard label="Handoffs مفتوحة" value={summary.open_handoffs} detail="محتاجة متابعة بشرية" icon={MessageSquareMore}/><StatCard label="Channels شغالة" value={summary.active_channels} detail="اتصالات Active" icon={RadioTower}/><StatCard label="Automation failures" value={summary.failed_automation_jobs} detail="Jobs محتاجة مراجعة" icon={CircleAlert}/></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.85fr]"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>أقرب الحجوزات</CardTitle><Link href="/appointments" className="text-sm font-bold text-teal-700">عرض الكل</Link></CardHeader><CardContent className="space-y-3">{summary.recent_appointments.length?summary.recent_appointments.map(a=><div key={a.id} className="flex flex-col gap-3 rounded-xl border border-[var(--border)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-bold">{a.patient_name}</div><div className="mt-1 text-xs text-[var(--muted)]">{a.service_name} · {a.branch_name} · {a.doctor_name}</div></div><div className="flex items-center gap-3"><div className="text-sm font-semibold">{formatDateTime(a.start_at)}</div><Badge tone={toneForStatus(a.status)}>{appointmentLabels[a.status]||a.status}</Badge><span className="text-xs text-[var(--muted)]">{formatMoney(a.price_minor,a.currency)}</span></div></div>):<div className="py-12 text-center text-sm text-[var(--muted)]">مفيش حجوزات جاية.</div>}</CardContent></Card>
 <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Team Inbox</CardTitle><Link href="/inbox" className="text-sm font-bold text-teal-700">فتح الـInbox</Link></CardHeader><CardContent className="space-y-3">{handoffs.length?handoffs.map(h=><Link key={h.id} href={`/inbox/${h.conversation_id}`} className="block rounded-xl border border-[var(--border)] p-4 hover:bg-[var(--surface-2)]"><div className="flex items-center justify-between"><b className="text-sm">{h.patient_name}</b><Badge tone={toneForStatus(h.priority)}>{h.priority}</Badge></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-[var(--muted)]">{h.reason}</p></Link>):<div className="py-12 text-center text-sm text-[var(--muted)]">الـInbox فاضي 🎉</div>}</CardContent></Card></div></>;
}
